drop user swc;

CREATE USER swc
  IDENTIFIED BY swc
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
  -- 20 System Privileges for swc
  GRANT CREATE ANY CONTEXT TO swc;
  GRANT CREATE CLUSTER TO swc;
  GRANT CREATE DATABASE LINK TO swc;
  GRANT CREATE INDEXTYPE TO swc;
  GRANT CREATE MATERIALIZED VIEW TO swc;
  GRANT CREATE OPERATOR TO swc;
  GRANT CREATE PROCEDURE TO swc;
  GRANT CREATE SEQUENCE TO swc;
  GRANT CREATE SESSION TO swc;
  GRANT CREATE SYNONYM TO swc;
  GRANT CREATE TABLE TO swc;
  GRANT CREATE TRIGGER TO swc;
  GRANT CREATE TYPE TO swc;
  GRANT CREATE VIEW TO swc;
  GRANT DEBUG ANY PROCEDURE TO swc;
  GRANT DEBUG CONNECT SESSION TO swc;
  GRANT DROP ANY CONTEXT TO swc;
  GRANT SELECT ANY DICTIONARY TO swc;
  GRANT SELECT ANY TABLE TO swc;
  GRANT UNLIMITED TABLESPACE TO swc;
  -- 2 Object Privileges for swc 
  GRANT EXECUTE ON SYS.DBMS_CRYPTO TO swc;
  GRANT EXECUTE ON SYS.DBMS_SESSION TO swc;
